### ISSUE TITLE
"Circles Counter" module - ограничение ширины тайтла

### ISSUE THREAD

**Issue by schelkunoff** [templatemonster/power-builder#5]
"Circles Counter" когда большой заголовок в модуле, а сам счетчик небольшой по ширине, то выходит очень не красиво, и при ресайзе, все еще хуже выглядит. Было бы хорошо сделать тайтл на всю ширину колонки. http://prntscr.com/dlnmxu

**Comment by shinTM** [comment]
upd: https://github.com/templatemonster/power-builder/commit/c6bf0d125603f736d75936f33df347fb0271177e
