### ISSUE TITLE
контакт форма

### ISSUE THREAD

**Issue by gurkoanna** [templatemonster/power-builder#7]
тут саппорт пишет - Привет . клиент с м2, спросил сегодня как добавить аттачмент в контакт форму, нет такого типа поля там к сожалению http://prntscr.com/dxy5hv . думаю имеет смысл добавить они это часто хотят

https://jira.devoffice.com/browse/QAS-67

**Comment by shinTM** [comment]
Там это сделать невозможно, потому сделали интеграцию в павербилдер форм contact form 7. А эту форму нужно выпилить
